Automated update

diff --git a/ubuntu_ovpn b/ubuntu_ovpn
--- a/ubuntu_ovpn
+++ b/ubuntu_ovpn
@@ -6,6 +6,7 @@ PASS='meteljep_paid';
 DBNAME='meteljep_paid';
 PORT_TCP='1194';
 PORT_UDP='53';
+DOMAIN='paid.bytesph.com/livewire/message/add-server';
 timedatectl set-timezone Asia/Riyadh
 install_require () {
 clear
@@ -214,21 +215,28 @@ sed -i "s|DBNAME|$DBNAME|g" /etc/openvpn/login/config.sh
 
 /bin/cat <<"EOM" >/etc/openvpn/login/auth_vpn
 #!/bin/bash
-. /etc/openvpn/login/config.sh
-Query="SELECT user_name FROM users WHERE user_name='$username' AND auth_vpn=md5('$password') AND is_freeze='0' AND duration > 0"
-user_name=`mysql -u $USER -p$PASS -D $DB -h $HOST -sN -e "$Query"`
-[ "$user_name" != '' ] && [ "$user_name" = "$username" ] && echo "user : $username" && echo 'authentication ok.' && exit 0 || echo 'authentication failed.'; exit 1
+data=$(curl -sb -X POST $DOMAIN/api/server/login -H "Content-Type: application/x-www-form-urlencoded" -d "login=true&username=$username&password=$password")
+
+if [[ $data == "ACCEPT" ]];
+then
+	echo $data
+	echo "$username | $password is valid"
+	exit 0
+else
+	echo $data
+	echo "$username | $password is invalid"
+	exit 1
+fi
 EOM
 
 #client-connect file
 cat <<'LENZ05' >/etc/openvpn/login/connect.sh
 #!/bin/bash
-. /etc/openvpn/login/config.sh
+
 ##set status online to user connected
 server_ip=SERVER_IP
-datenow=`date +"%Y-%m-%d %T"`
-mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE users SET is_connected='1', device_connected='1', active_address='$server_ip', active_date='$datenow' WHERE user_name='$common_name' "
-mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online=online+1 WHERE server_ip='$server_ip' "
+data=$(curl -sb -X POST $DOMAIN/api/server/update-status -H "Content-Type: application/x-www-form-urlencoded" -d "status=1&username=$common_name&ip=$server_ip")
+
 LENZ05
 
 sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/connect.sh
@@ -236,13 +244,12 @@ sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/connect.sh
 #TCP client-disconnect file
 cat <<'LENZ06' >/etc/openvpn/login/disconnect.sh
 #!/bin/bash
-. /etc/openvpn/login/config.sh
-server_ip=SERVER_IP
-mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE users SET is_connected='0', active_address='', active_date='' WHERE user_name='$common_name' "
-mysql -u $USER -p$PASS -D $DB -h $HOST -e "UPDATE server_list SET online=online-1 WHERE server_ip='$server_ip' "
+
+data=$(curl -sb -X POST $DOMAIN/api/server/update-status -H "Content-Type: application/x-www-form-urlencoded" -d "status=0&username=$common_name")
+
 LENZ06
 
-sed -i "s|SERVER_IP|$server_ip|g" /etc/openvpn/login/disconnect.sh
+
 
 cat << EOF > /etc/openvpn/easy-rsa/keys/ca.crt
 -----BEGIN CERTIFICATE-----
